
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-01
owner: ucsb-cs156-f25
repo_name: team02-f25-01
pull_requests: [{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jv-HelpRequest-index-page","number":120,"title":"jv - Index Page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/120"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequests-e2e-tests","number":115,"title":"wc - recommendationrequests e2e tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/115"},{"author":{"id":"U_kgDOCO5ODw","is_bot":false,"login":"noahzlouie","name":"Noah Louie"},"headRefName":"nl-MenuItemReview-edit","number":114,"title":"nl - added menu item review edit page","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/114"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequests-integration-tests","number":113,"title":"wc - recommendationrequests integration tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/113"},{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jv-HelpRequest-create-page","number":108,"title":"jv - Create Page for HelpRequest plus tests and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/108"}]
