
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-01
owner: ucsb-cs156-f25
repo_name: team02-f25-01
pull_requests: [{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-copy","number":70,"title":"yl - copy UCSBOrganization files","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/70"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequest-fixtures","number":69,"title":"wc - add javascript fixtures for recommendationrequest table","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/69"},{"author":{"id":"U_kgDOCO5ODw","is_bot":false,"login":"noahzlouie","name":"Noah Louie"},"headRefName":"nl-MenuItemReview-backend","number":68,"title":"nl - copy backend CRUD operations from team01 for the MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/68"}]
