
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-01
owner: ucsb-cs156-f25
repo_name: team02-f25-01
pull_requests: [{"author":{"id":"U_kgDOBkhdrg","is_bot":false,"login":"nicxs3","name":"Nic Santos"},"headRefName":"ns-Articles-E2E-test","number":133,"title":"ns - Articles e2e test","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/133"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequest-e2e-tests","number":131,"title":"wc - recommendationrequests e2e tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/131"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequest-integration-tests","number":130,"title":"wc - recommendationrequests integration tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/130"},{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-webit","number":125,"title":"yl - create e2e tests for UCSB Organizations","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/125"},{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-team03","number":124,"title":"yl - add Integration tests for UCSBOrganizations","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/124"},{"author":{"id":"U_kgDOCl4-hw","is_bot":false,"login":"ngostream","name":"Nathan Ngo"},"headRefName":"nn-nn-end2endtest-ucsbdiningcommonsmenuitem","number":122,"title":"nn - end2endtest ucsbdiningcommonsmenuitem","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/122"}]
