
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-01
owner: ucsb-cs156-f25
repo_name: team02-f25-01
pull_requests: [{"author":{"id":"U_kgDOCl4-hw","is_bot":false,"login":"ngostream","name":"Nathan Ngo"},"headRefName":"nn-form-component-UCSBDiningCommonsMenuItem","number":78,"title":"nn - form component ucsb dining commons menu item","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/78"},{"author":{"id":"U_kgDOBkhdrg","is_bot":false,"login":"nicxs3","name":"Nic Santos"},"headRefName":"ns-Articles-fixtures","number":77,"title":"ns - created Articles Fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/77"},{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jv-HelpRequest-fixtures","number":74,"title":"jv - Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/74"},{"author":{"id":"U_kgDOCSk7nw","is_bot":false,"login":"jjohnvu","name":""},"headRefName":"jv-HelpRequest-backend-crud","number":73,"title":"jv - Copy files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/73"},{"author":{"id":"U_kgDOBwqWJQ","is_bot":false,"login":"WLL1am","name":"William Chung"},"headRefName":"wc-recommendationrequest-form","number":72,"title":"wc - add form for RecommendationRequests","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/72"},{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-fixtures-ucsbOrg","number":71,"title":"yl - create fixtures for ucsbOrganizations","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/71"},{"author":{"id":"U_kgDOB7yQrQ","is_bot":false,"login":"WilliamLinA","name":""},"headRefName":"yl-copy","number":70,"title":"yl - copy UCSBOrganization files","url":"https://github.com/ucsb-cs156-f25/team02-f25-01/pull/70"}]
